services:
  - type: web
    name: nextjs-service
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:/opt/render/project/src/production.db
    disk:
      name: database
      mountPath: /opt/render/project/src
      sizeGB: 1
