services:
  - type: web
    name: nextjs-service
    env: node
    plan: starter
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: nextjs-database
    databaseName: nextjs_service
    user: nextjs_user
